### ISSUE TITLE
Updated Code

### ISSUE THREAD

**Issue by mnchrm** [mpiraux/CMD-DC-1-Ableton-9-Control-Surface-Script#10]
Hello, my name is Monochrome and i'm a music producer. I've been using your DC-1 script for years now, and it's great, i'd like to thank you for that.

After Ableton Live updated to 11, however, the code stopped working, and when i came back to this, you seemed to have discontinued support for the new versions of the code, so i've modified it myself, and it's now updated to Python 3, and running okay on Live 11. I'd like to ask your permission to re-host the code on my own github (all credits to you, of course), or to make a PR with the updated code.

Thanks in advance

Mnchrm

**Comment by mpiraux** [comment]
Of course, you don't have to ask for permission ;) Thanks for taking the time to update the script! You can PR the repo whenever you have changes that you want to share with others.

**Comment by mnchrm** [comment]
I already made a PR to the code, though i'm quite inexperienced with git, so i'm not sure i did it correctly...

thanks in advance

mnchrm

________________________________
