### ISSUE TITLE
Live 11?

### ISSUE THREAD

**Issue by lkjts** [mpiraux/CMD-DC-1-Ableton-9-Control-Surface-Script#12]
Hi there, I tried to install this script in Live 11 but the device does not show up in th drop-down list. I'm pretty sure I installed it correctly (it worked fine for Live 9 before). Any tips?

**Comment by mpiraux** [comment]
If that's still relevant, look for #13 and try placing it at `C:\ProgramData\Ableton\Live 11 Suite\Resources\MIDI Remote Script`.
