### ISSUE TITLE
Correct Installation Directory

### ISSUE THREAD

**Issue by ChrisMills83** [mpiraux/CMD-DC-1-Ableton-9-Control-Surface-Script#13]
Hey, I'm pretty sure this is a dead project, but I wanted to leave this here in case you are still at all active and wanted to make a correction.  Your installation instructions on where to put the script folder and scripts is incorrect (on Windows 10 at least).

The directory where the folder for the scripts are located is C:\ProgramData\Ableton\Live 11 Suite\Resources\MIDI Remote Scripts.  When I placed it where you specified on the installation instructions nothing showed up, but placing it here worked like a charm.

Credit to Behringer's original script, for which the download linked on their product page contained a PDF with instructions that directed me on where to install this to where I was able to get it working.

**Comment by mpiraux** [comment]
Thanks for this! I'm not using the hardware nor the software anymore but it looks like this will be helpful to others.

**Comment by ChrisMills83** [comment]
Yes, in Ableton Live 11.
