### ISSUE TITLE
Global_Channel

### ISSUE THREAD

**Issue by pavallin** [mpiraux/CMD-DC-1-Ableton-9-Control-Surface-Script#2]
Hi Maxime, and thank you VERY MUCH for this update!!

I had an issue with your script, but a very simple one: for some reason, my DC-1 came configured on channel 1, instead of 6 as it should be. Nothing was working, until I changed GLOBAL_CHANNEL from 5 to 0. It is now perfect! :)

I suggest you spread your scripts to the Ableton forums and more, people who bought the DC-1 would be extremely pleased to see this update.
If, as your name suggests, and as I am, you are from France, the Audiofanzine forum would also be a great place to share your scripts.

Cheers!
Pierre-Augustin.

**Comment by pavallin** [comment]
BTW, I'm currently learning Python and Ableton scripting, I'm considering adapting your scripts to my needs, ie un-mapping the "pads" to clips and being able to manually map them to selecting effect racks; the encoders would then act as normal, macro controllers.

**Comment by mpiraux** [comment]
Hi!

I read somewhere that some early production model of the DC-1 came up with the midi output on channel 1. I'm thinking of adding this to the readme, now that you're reporting this issue. Thank you for the feedback.
As for your suggestion, I didn't checked if Ableton's forums had a special section nor thought about other places than Behringer forum. I'll do this asap. I'm actually a native French speaker but I maintain this repository in English so people can read anything they want ;)

I've also planned to create a script combining the DC-1 and LC-1 into a more capable controller. I'll publish it on github as soon as I'm ok with. For the time being, I've not started development nor properly planned a time to do so.

**Comment by pavallin** [comment]
Hi Maxime,

I'm glad to hear that! Hope everything goes well :)

I'll follow you and see what you do :)

Cheers!
Pierre-Augustin
