### ISSUE TITLE
script is there, but control isn't

### ISSUE THREAD

**Issue by unclenoah** [mpiraux/CMD-DC-1-Ableton-9-Control-Surface-Script#7]
I put the script in the proper folder.  I checked the MIDI channel assignment utility against the script and everything is set to channel 5.  I can select the control surface in the MIDI preferences, and I've got Track and Remote set to on for the Ins and Outs.  I get the 4x4 pink box in the clip launch view, plus the box around the 4 scenes on the right, but the big knob doesn't make the box move, and none of the buttons trigger the clips.  The MIDI input light in the upper right of Live blinks when I hit pads and twist knobs on the DC-1 so I have to be close, I just can't figure out why it isn't working.
[Log.txt](https://github.com/mpiraux/CMD-DC-1-Ableton-9-Control-Surface-Script/files/419549/Log.txt)

**Comment by mpiraux** [comment]
Hello,

I've never tried my script with Ableton 9.6 actually. So I can't confirm that it is working past version 9.5. But if you set your DC-1 to MIDI Channel 5 (which is labeled as channel 6 in the utility) and got the 4x4 box, that means the script initialized correctly but is broken or either not receiving MIDI messages. The fault is not on your side I guess.
I'm not using Ableton anymore at the moment, so I can't promise any ETA of this fix. But if I fix it one day,  I'll keep you posted about this.

Have a good day.

**Comment by unclenoah** [comment]
I didn't know about the channel 6 = channel 5 in the utility thing! I had the utility set for utility channel 5! I'll try this out tonight and I bet you it's going to work! Thanks for that piece of info!!

**Comment by unclenoah** [comment]
That did it!!  That's the big trick to the whole thing -- the Channel Chooser is 1 value off!  Setting the Channel Chooser to 6 and making sure the script is set to 5 made it all work!  Thanks again for helping with this - because of you, I will now proceed to viciously throw down on my box.
